//! Draft a Zonewarden segmentation policy from a capture's asset inventory
//! (ADR-0013). This is the bootstrap that standalone zonewarden could never do:
//! otsniff already infers host roles (PLC / HMI / EWS / historian / IT), which
//! is most of "what Purdue level is this subnet." We group hosts into subnets,
//! infer each zone's level from the dominant role, and emit a reviewable draft
//! `zones.yaml`. Conduits are left empty on purpose — deny-by-default means the
//! analyst sees every cross-zone flow and whitelists the intended ones.

use std::collections::BTreeMap;
use std::net::IpAddr;

use crate::inventory::{Asset, Role};

/// Render a draft policy YAML from the inventory. Deterministic (subnets sorted).
pub fn draft_policy(inventory: &[Asset]) -> String {
    let mut groups: BTreeMap<String, Vec<&Asset>> = BTreeMap::new();
    for a in inventory {
        groups.entry(subnet_of(a.ip)).or_default().push(a);
    }

    let mut out = String::new();
    out.push_str(
        "# Draft Zonewarden segmentation policy — generated by `otsniff zonewarden suggest`.\n\
         # Zones are inferred from observed subnets; Purdue levels from inferred asset roles.\n\
         # REVIEW BEFORE USE: verify the levels, merge/split zones as needed, and add conduits\n\
         # for the flows you intend to permit. Deny-by-default — every cross-zone flow is\n\
         # reported until a conduit allows it. Then run:\n\
         #   otsniff analyze <pcap> --policy <this-file>\n\
         zones:\n",
    );
    for (cidr, assets) in &groups {
        let level = dominant_level(assets);
        out.push_str(&format!("  - id: {}\n", zone_id(cidr)));
        out.push_str(&format!(
            "    name: \"{cidr} — {}\"\n",
            role_summary(assets)
        ));
        out.push_str(&format!("    purdue_level: {level}\n"));
        out.push_str(&format!("    members: [\"{cidr}\"]\n"));
    }
    out.push_str("conduits: []  # TODO: add the cross-zone flows you intend to permit\n");
    out
}

/// The /24 (IPv4) or /64 (IPv6) the address belongs to, as a CIDR string.
fn subnet_of(ip: IpAddr) -> String {
    match ip {
        IpAddr::V4(v4) => {
            let o = v4.octets();
            format!("{}.{}.{}.0/24", o[0], o[1], o[2])
        }
        IpAddr::V6(v6) => {
            let s = v6.segments();
            format!("{:x}:{:x}:{:x}:{:x}::/64", s[0], s[1], s[2], s[3])
        }
    }
}

/// A reference-able zone id derived from the CIDR (non-alphanumerics → `_`).
fn zone_id(cidr: &str) -> String {
    let mut id = String::from("z_");
    id.extend(
        cidr.chars()
            .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' }),
    );
    id
}

/// Purdue level for a role. Conservative middle (L3) for ambiguous roles.
fn role_level(role: Role) -> &'static str {
    match role {
        Role::Plc => "L1",
        Role::Hmi => "L2",
        Role::EngineeringWorkstation | Role::Historian | Role::NetworkInfra => "L3",
        Role::ItEndpoint => "L4",
        Role::Unknown => "L3",
    }
}

/// A small numeric rank so ties break toward the most-OT (lowest) level.
fn level_rank(level: &str) -> u8 {
    match level {
        "L1" => 1,
        "L2" => 2,
        "L3" => 3,
        "L4" => 4,
        _ => 3,
    }
}

/// The zone's level = the level of the most common role; ties break to the
/// most-OT (lowest) level so a subnet with any PLCs reads as a control zone.
fn dominant_level(assets: &[&Asset]) -> &'static str {
    let mut counts: BTreeMap<&'static str, usize> = BTreeMap::new();
    for a in assets {
        *counts.entry(role_level(a.role)).or_default() += 1;
    }
    counts
        .into_iter()
        .max_by(|(la, ca), (lb, cb)| {
            ca.cmp(cb).then_with(|| level_rank(lb).cmp(&level_rank(la))) // lower level wins ties
        })
        .map(|(level, _)| level)
        .unwrap_or("L3")
}

/// "3 PLC, 1 IT endpoint" — the role mix, most-common first, for the zone name.
fn role_summary(assets: &[&Asset]) -> String {
    let mut counts: BTreeMap<&'static str, usize> = BTreeMap::new();
    for a in assets {
        *counts.entry(a.role.label()).or_default() += 1;
    }
    let mut v: Vec<(&'static str, usize)> = counts.into_iter().collect();
    v.sort_by(|a, b| b.1.cmp(&a.1).then(a.0.cmp(b.0)));
    v.iter()
        .map(|(label, n)| format!("{n} {label}"))
        .collect::<Vec<_>>()
        .join(", ")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn asset(ip: &str, role: Role) -> Asset {
        Asset {
            ip: ip.parse().unwrap(),
            hostname: None,
            mac: None,
            vendor: None,
            role,
            protocols: Vec::new(),
            packets: 1,
            bytes: 1,
            in_ot_zone: false,
        }
    }

    #[test]
    fn groups_by_subnet_and_infers_levels() {
        let inv = vec![
            asset("10.0.1.5", Role::Plc),
            asset("10.0.1.6", Role::Plc),
            asset("192.168.2.10", Role::ItEndpoint),
        ];
        let yaml = draft_policy(&inv);
        assert!(yaml.contains("members: [\"10.0.1.0/24\"]"));
        assert!(yaml.contains("members: [\"192.168.2.0/24\"]"));
        // PLC subnet → L1; IT subnet → L4.
        assert!(yaml.contains("purdue_level: L1"));
        assert!(yaml.contains("purdue_level: L4"));
    }

    #[test]
    fn draft_round_trips_through_the_policy_loader() {
        // The whole point: a drafted policy must be valid input to the engine.
        let inv = vec![
            asset("10.0.1.5", Role::Plc),
            asset("192.168.2.10", Role::ItEndpoint),
            asset("172.16.4.4", Role::Hmi),
        ];
        let yaml = draft_policy(&inv);
        let parsed = crate::segmentation::policy::load_str(&yaml).expect("draft parses");
        zonewarden::validator::validate(parsed).expect("draft validates");
    }

    #[test]
    fn ties_break_to_most_ot_level() {
        // One PLC (L1) + one IT (L4) in the same /24 → tie on count, L1 wins.
        let inv = vec![
            asset("10.0.9.1", Role::Plc),
            asset("10.0.9.2", Role::ItEndpoint),
        ];
        let yaml = draft_policy(&inv);
        assert!(yaml.contains("purdue_level: L1"));
    }
}
